### ISSUE TITLE
WorkflowTaskArguments: Cannot expand a list with an object

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#117]
For some tasks (=> multiplexing create ome zarr), we need to have lists within an object. In that case, I can toggle the object to show its content. But I can't show the content of each list anymore

See video here: https://drive.google.com/file/d/1CCe4JU1FoW6zxekF7LhKCXO4byopI_qB/view?usp=sharing

**Comment by jluethi** [comment]
```
dex.js:62 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#2' is not a valid selector.
    at i (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:543)
    at HTMLButtonElement.<anonymous> (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:20549)
    at HTMLDocument.n (https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js:6:4135)
i @ index.js:62
(anonymous) @ collapse.js:288
n @ event-handler.js:118
```
