### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#12]
Environment:
```
$ npm -v
9.4.0

$ node -v
v19.6.1

$ npm view svelte
svelte@3.55.1 | MIT | deps: none | versions: 446
[...]
```

Steps to reproduce:
* git clone the repo, and switch to the `development` branch;
* Write `PUBLIC_BACKEND_URL=http://127.0.0.1:8000` in a `.env` file;
* `npm run dev -- --open`
* Head to `http://localhost:5173/auth/login`, try to login with standard credentials.
* The running instance of fractal-server receives nothing, the login doesn't work, and by the inspect tool I have a 500 error

**Comment by tcompa** [comment]
@mfranzon has a different but possibly related issue in starting up the frontend. Even before heading to the login page, he finds:
```
Cannot read properties of undefined (reading 'get')
TypeError: Cannot read properties of undefined (reading 'get')
    at load (/src/routes/auth/login/+page.server.js:4:31)
    at load_server_data (file:///home/marco/exact/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:31:41)
    at file:///home/marco/exact/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/data/index.js:57:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async render_data (file:///home/marco/exact/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/data/index.js:94:17)
    at async resolve (file:///home/marco/exact/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/index.js:258:17)
    at async respond (file:///home/marco/exact/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/index.js:345:10)
    at async file:///home/marco/exact/fractal-web/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:385:22
```

**Comment by rkpasia** [comment]
The application uses a different env var instead of `PUBLIC_BACKEND_URL` as referenced here: [`import { PUBLIC_FRACTAL_SERVER_HOST } from '$env/static/public'`](https://github.com/fractal-analytics-platform/fractal-web/blob/b2bfed38d220a85b3e839ba52aa8849fb1902c59/src/routes/auth/login/%2Bpage.server.js#L1)

We can discuss to update the name of such .env var obviously.

Try to update the var name and it should resolve this issue?

_For sure a better explanation/feedback in the client could/should be considered._

**Comment by tcompa** [comment]
`PUBLIC_FRACTAL_SERVER_HOST` is fine, we should just document it somewhere - ref https://github.com/fractal-analytics-platform/fractal-web/issues/5
