### ISSUE TITLE
Login fails on new branch

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#134]
I tried with branch sveltekit-server-api-proxy, and fractal-server 1.2.5.
The login action fails, with no obvious errors in the browser.
The vite console logs are
```
(base) fractal@fractal-server-dev:/data/active/fractal/deployments/tmp_server_04/fractal-web$ npm run dev

> fractal-app@0.0.1 dev
> vite dev


Port 5173 is in use, trying another one...

  VITE v4.2.2  ready in 974 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
  ➜  press h to show help
SSR - Main layout
SSR - Main layout
Server info loaded: Alive true - 1.2.5 - testing
Server info loaded: Alive true - 1.2.5 - testing
Error loading user info
Error: Unable to fetch user identity
    at Module.whoami (/src/lib/server/api/v1/auth_api.js:35:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (/src/routes/+layout.server.js:34:20)
    at async Module.load_server_data (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:49:17)
    at async eval (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13)
Error loading user info
Error: Unable to fetch user identity
    at Module.whoami (/src/lib/server/api/v1/auth_api.js:35:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (/src/routes/+layout.server.js:34:20)
    at async Module.load_server_data (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:49:17)
    at async eval (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13)
SSR - Main layout
Server info loaded: Alive true - 1.2.5 - testing
Error loading user info
Error: Unable to fetch user identity
    at Module.whoami (/src/lib/server/api/v1/auth_api.js:35:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (/src/routes/+layout.server.js:34:20)
    at async Module.load_server_data (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:49:17)
    at async eval (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13)
SSR - Main layout
Server info loaded: Alive true - 1.2.5 - testing
Error loading user info
Error: Unable to fetch user identity
    at Module.whoami (/src/lib/server/api/v1/auth_api.js:35:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async load (/src/routes/+layout.server.js:34:20)
    at async Module.load_server_data (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:49:17)
    at async eval (/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:150:13)
12:55:42 PM [vite-plugin-svelte] ssr compile done.
package    	files	  time	   avg
fractal-app	    3	62.8ms	20.9ms
```

**Comment by tcompa** [comment]
Note: this is actually with a specific setup, which involves SSH port forwarding and CORS.
I need to debug further.

**Comment by tcompa** [comment]
Fractal-server logs:
```
INFO:     127.0.0.1:58232 - "POST /auth/token/login HTTP/1.1" 200 OK
INFO:     127.0.0.1:58232 - "GET /api/alive/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:58246 - "GET /auth/whoami HTTP/1.1" 401 Unauthorized
```

**Comment by tcompa** [comment]
Fixed by setting FRACTAL_SERVER_HOST=http://localhost:8000 instead of 127.0.01

**Comment by tcompa** [comment]
For the record: this means that we were able to use fractal-web on a remote machine with a single ssh tunnel (the one for the fractal-web port), but without port-forwarding for fractal-server.

More debugging soon

**Comment by rkpasia** [comment]
Using `localhost` instead of `127.0.0.1` is required by the browser in order to accept the cookie that is sent by the client's server.

Using `127.0.0.1` does not match the `localhost` domain of the client's server, which in the end does not get stored in the browser and used to authenticate following requests through node server.

I don't understand what do you mean by:
> [...] we were able to use fractal-web on a remote machine with a single ssh tunnel [...]
