### ISSUE TITLE
`AUTH_COOKIE_NAME` error in `npm run build`

### ISSUE THREAD

**Issue by tcompa** [fractal-analytics-platform/fractal-web#141]
```
"AUTH_COOKIE_NAME" is not exported by "$env/static/private", imported by "src/routes/auth/logout/+server.js".
file: /xxx/server_05_to_use_apache/fractal-web/src/routes/auth/logout/+server.js:4:1
2: import { logout } from '$lib/server/api/v1/auth_api'
3: import {
4:   AUTH_COOKIE_NAME,
     ^
5:   AUTH_COOKIE_DOMAIN,
6:   AUTH_COOKIE_PATH,
error during build:
RollupError: "AUTH_COOKIE_NAME" is not exported by "$env/static/private", imported by "src/routes/auth/logout/+server.js".
    at error (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at Module.error (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:13340:16)
    at Module.traceVariable (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:13725:29)
    at ModuleScope.findVariable (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:12240:39)
    at FunctionScope.findVariable (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:6980:38)
    at ChildScope.findVariable (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:6980:38)
    at Identifier.bind (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:8130:40)
    at CallExpression.bind (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:5743:28)
    at CallExpression.bind (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:9659:15)
    at ExpressionStatement.bind (file:///xxx/server_05_to_use_apache/fractal-web/node_modules/rollup/dist/es/shared/node-entry.js:5747:23)
```

**Comment by tcompa** [comment]
I think this is because `.env.developement` is not being used.

**Comment by tcompa** [comment]
> I think this is because `.env.developement` is not being used.

I confirm. If I move all its content to `.env`, then the build succeeds.
