### ISSUE TITLE
On Login attempt: `Cannot read properties of undefined (reading 'get')`

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-web#23]
When I start the webserver with the current instructions from the README and using Node.js 18, I get to the login page. When trying to log in, I hit the following error:

```
500
Cannot read properties of undefined (reading 'get')
TypeError: Cannot read properties of undefined (reading 'get')
    at load (/src/routes/auth/login/+page.server.js:4:31)
    at load_server_data (file:///Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:31:41)
    at file:///Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/data/index.js:57:13
    at async Promise.all (index 1)
    at async render_data (file:///Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/data/index.js:94:17)
    at async resolve (file:///Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/index.js:258:17)
    at async respond (file:///Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-web/node_modules/@sveltejs/kit/src/runtime/server/index.js:345:10)
    at async file:///Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-web/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:385:22
```

This shows up both in the terminal and the web interface.

In the terminal running it, I additionally get:
```
3:47:26 PM [vite-plugin-svelte] /Users/joel/Dropbox/Joel/FMI/Code/fractal/fractal-web/src/routes/auth/login/+page.svelte:7:13 Page has unused export property 'data'. If it is for external reference only, please consider using `export const data`
```

**Comment by tcompa** [comment]
`npm list` output would be useful

**Comment by jluethi** [comment]
I went through all the instructions again with the current main and now the login works.

The only thing I did different was that last time, I had not used nvm and only installed Node.js 18. Now I went with the commands as listed in the README and I can log in.

**Comment by rkpasia** [comment]
> and now the login works

Enjoy it!

**Comment by jluethi** [comment]
Now you'll also start to get issues from me, given that I can also test it 😅😇
